### ISSUE TITLE
Feature request: fish support

### ISSUE THREAD

**Issue by lofidevops** [dbarnett/python-selfcompletion#2]
Would it be possible to also support completions in fish? https://github.com/fish-shell/fish-shell

See also:
- http://ridiculousfish.com/shell/user_doc/html/index.html#completion-own
- https://github.com/fish-shell/fish-shell/issues/1217
- http://stackoverflow.com/questions/20838284/how-can-i-provide-tab-completions-to-fish-shell-from-a-python-script

**Comment by dbarnett** [comment]
Yep, that was actually my motivation for starting this project. It's listed in the TODO as well.

The mechanism I use for bash is to register a "default" completion script so any executable on the system will try selfcompletion if it doesn't have its own custom completion script. I was hoping to find a similar mechanism (to delegate to a default script) in fish and other shells, but so far I haven't found any. If nothing else, this might entail creating a stub for each executable you want selfcompletion-based completion for, and having that forward to `--_completion`.

Also for fish, the completion includes fancy descriptions and such (beyond just the standard list of suggested strings) that selfcompletion doesn't have any support for yet.

**Comment by lofidevops** [comment]
Thanks for the clarification. I had forgotten about the TODO and thought I had just dreamed that fish support had been mentioned. So, an alternate solution would be to update fish itself to attempt a --_completion call when the user hits tab? Sounds like a friendly and interactive option :D

**Comment by lofidevops** [comment]
See https://github.com/fish-shell/fish-shell/issues/1217#issuecomment-31441757 for a suggestion on dynamic completions with `--_completion`

**Comment by lofidevops** [comment]
Closing since resolved in fish ticket (pending documentation).
